// Generated by CoffeeScript 1.4.0
(function() {

  window.Helpers = (function() {

    function Helpers() {}

    Helpers.wrapped_function = /[try]+[\s]*[\{]*[.*]*[Jacket\.handle]+/;

    return Helpers;

  })();

}).call(this);
