// Generated by CoffeeScript 1.4.0
(function() {

  this.BackboneView = Backbone.View.extend({
    render: function() {
      return 'render';
    },
    myCrazyMethod: function() {
      return 'lol';
    }
  });

}).call(this);
