// Generated by CoffeeScript 1.4.0
(function() {

  window.Examples.BackboneView = Backbone.View.extend({
    constructor: function() {
      return fsdf;
    },
    render: function() {
      return 'render';
    },
    myCrazyMethod: function() {
      return 'lol';
    }
  });

}).call(this);
