// Generated by CoffeeScript 1.4.0
(function() {

  window.BackboneView = J(Backbone.View, {
    constructor: function() {
      return fsdf;
    },
    render: function() {
      return 'render';
    },
    myCrazyMethod: function() {
      return 'lol';
    }
  });

}).call(this);
