// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  describe('Backbone.View.extend', function() {
    before(function() {
      return this.W = Jacket(BackboneView);
    });
    return describe('Jacket ( BackboneView )', function() {
      it('should return new class', function() {
        return this.W.should.not.equal(BackboneView);
      });
      return describe('should have', function() {
        it('correct name', function() {
          return this.W.name.should.equal('OLOL');
        });
        return it('wrapped prototype methods of __super__', function() {
          var prop, val, _ref, _results;
          _ref = this.W.prototype;
          _results = [];
          for (prop in _ref) {
            if (!__hasProp.call(_ref, prop)) continue;
            val = _ref[prop];
            if (typeof val === 'function' && prop !== 'constructor') {
              console.log(' >>>> ', prop, val);
              _results.push(val.should.match(Helpers.wrapped_function));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
      });
    });
  });

}).call(this);
