// Generated by CoffeeScript 1.4.0
(function() {

  describe('Chaplin.js Jacket implementation', function() {
    return it('should be ready to test', function() {
      return true;
    });
  });

}).call(this);
